# description: configuration file path, if it's specified as relative path,
# then directory of binary file will be the base directory of configuration file,
# it is recommended to specify absolute path.
# type: string
# default: None
config: go_template.yaml

# specify whether das runs as daemon mode, if true, das will run as a daemon process.
# type: bool
# default: false
daemon: false

# log configuration
log:
  # description: log file path, if it's specified as relative path,
  # then directory of binary file will be the base directory of log file,
  # it is recommended to specify absolute path.
  # type: string
  # default: log/run.log
  file: log/run.log
  # description: log level
  # type: string
  # available: [debug, info, warn, error, fatal]
  # default: info
  level: info
  # description: log format
  # type: string
  # available: [text, json]
  # default: text
  format: text
  # description: log file max size, unit is MB
  # type: int
  # default: 100
  maxSize: 100 # MB
  # description: specify how many days the log file will be kept after rotating,
  # older than max-days files will be removed automatically.
  # type: int
  # default: 7
  maxDays: 7
  # description: specify how many files will be kept after rotating,
  # the oldest log files will be removed automatically.
  # type: int
  # default: 5
  maxBackups: 5

# lex subcommand section
lex:
  # description: specify the finite automata of the lexer
  # type: string
  # available: [nfa, dfa]
  # default: nfa
  finiteAutomata: nfa

# parse subcommand section
parse:
  # specify the lexer configuration
  lexer:
    # description: specify the finite automata of the lexer
    # type: string
    # available: [nfa, dfa]
    # default: nfa
    finiteAutomata: nfa
  # specify the parser configuration
  parser:
    # description: specify the finite automata of the parser
    # type: string
    # available: [nfa, ll]
    # default: ll
    finiteAutomata: ll

# description: specify the sql text
# type: string
# default: ""
sql: ""
